#!/usr/bin/env python

import sys
import time
import paramiko
import os
import cmd
import datetime

hojadato = "backup_" + time.strftime("%Y-%m-%d-%H:%M:%S")

os.mkdir(hojadato, 0755)

comando_mover = "mv BKP-Switch-* "+hojadato

USER = "sbrito"
PASSWORD = "cisco"
#secret = "cisco"

f = open('cisco')
for ip in f.readlines():
       ip = ip.strip()
       filename_prefix = 'cisco_backup' + ip
       ssh = paramiko.SSHClient()
       ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
       ssh.connect (ip, username=USER, password=PASSWORD)
       chan = ssh.invoke_shell()
       time.sleep(2)
       chan.send('enable\n')
       #chan.send(secret +'\n')
       time.sleep(1)
       chan.send('term len 0\n')
       time.sleep(1)
       chan.send('sh run\n')
       time.sleep(10)
       output = chan.recv(99999)
       print output
       crear_archivo = open("BKP-Switch-"+hojadato+"-"+ip,"w")
       crear_archivo.write(output)
       crear_archivo.close

       os.system(comando_mover)

       ssh.close()
       print ip
       f.close()
